version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MXMDeploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i52ufe9sdodq"
s3_prefix = "MXMDeploy"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "PREFIX=\"MXM\" ORIGIN=\"master.example.amplifyapp.com\" APIKEY=\"871cdaeaa43459b2e9d53a1d4ce3ff63\""

