AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample AWS SAM Template
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  PREFIX:
    Type: String
    Default: SAM
  ORIGIN:
    Type: String
    Default: master.example.amplifyapp.com
  APIBASE:
    Type: String
    Default: "https://api.musixmatch.com/ws/1.1/"
  APIKEY:
    Type: String
    Default: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${PREFIX}IamRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ApiEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub "${PREFIX}ApiEndpoint"
      Cors: "'*'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${PREFIX}Proxy"
      CodeUri: functions/musixmatch-proxy/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Role: !GetAtt IamRole.Arn
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiEndpoint
            Path: "/musixmatch-proxy/{proxy+}"
            Method: ANY
      Environment:
        Variables:
          apikey: !Sub "${APIKEY}"
          apibase: !Sub "${APIBASE}"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RestApi:
    Description: "API endpoint URLs for Proxy stage:"
    Value: !Sub "https://${ApiEndpoint}.execute-api.${AWS::Region}.amazonaws.com/${PREFIX}ApiEndpoint/musixmatch-proxy/" 
